### ISSUE TITLE
Settings screen

### ISSUE THREAD

**Issue by AboShanab** [sigillabs/mobidex#145]
We should make this issue for all the related things about Settings screen, here's my suggestions about the features:

Give the users ability to:
- Change the passcode
- Change the Timeout of passcode
- Ability to hide passcode when back to the application after a few minutes (when the user enable this, the passcode should be appears only when the application closed at all and not working on the background)
- Way to change the provider of gas info
- Way to change nonce and gas for the transaction (better than show it on every trade process)

**Comment by AboShanab** [comment]
Related: #143 #122 #81 #79 and #65.

**Comment by generalpiston** [comment]
Unnecessary with redesign.
