### ISSUE TITLE
Null pointer exceptions

### ISSUE THREAD

**Issue by AboShanab** [sigillabs/mobidex#146]
Hello there, I tested the latest version of the app and gets null pointer exceptions, which we should not get.

![img_20181016_211415_548](https://user-images.githubusercontent.com/12101368/47037860-c07d6180-d188-11e8-8e98-6683bf179004.jpg)

Best regards,
AboShanab.

**Comment by generalpiston** [comment]
The underlying library is throwing this exception. Should be fixed by #87. Let's leave this open until then though.

**Comment by generalpiston** [comment]
#87 is done... this should be fixed.
