### ISSUE TITLE
[wallet] rounding errors

### ISSUE THREAD

**Issue by AboShanab** [sigillabs/mobidex#187]
The un/wrap feature looks have a calculation bugs, exactly with 0.0004
![mobidex1](https://user-images.githubusercontent.com/12101368/50747661-29372000-1246-11e9-9dbf-0b3d4798a75c.jpg)
![mobidex2](https://user-images.githubusercontent.com/12101368/50747664-2dfbd400-1246-11e9-94c3-bddc678c37b1.jpg)

**Comment by generalpiston** [comment]
This happens when the account balance has more than 15 decimal places.

**Comment by generalpiston** [comment]
Actually, scratch that. It seems related to a 0x implementation: https://github.com/0xProject/0x-monorepo/blob/development/packages/web3-wrapper/src/web3_wrapper.ts#L98. We should be able to catch this.
