### ISSUE TITLE
[trade] redesign receipt

### ISSUE THREAD

**Issue by generalpiston** [sigillabs/mobidex#200]
Receipts for:
- [x] Fill order
- [x] Limit order
- [x] Send tokens
- [x] Send ethereum
- [ ] lock/unlock
- [x] Wrap/Unwrap ethereum

Details:
- [x] Relayer: fee, fee token
- [x] Network: gas, gas price, total network fee
- [x] Order Details: price, amount, side
- [x] Sending: tokens, amount
- [x] Receiving: tokens, amount
- [x] Wallet: network fee amount, relayer fee amount, receive token amount, send token amount
- [x] After Transaction Wallet: network fee amount, relayer fee amount, receive token amount, send token amount
- [ ] ~Expiration time~

**Comment by AboShanab** [comment]
Network:
We need to change value field to 'Transaction value' to be more clear.

**Comment by generalpiston** [comment]
Moving lock to a new ticket.
