### ISSUE TITLE
Orders & Settings UI bugs

### ISSUE THREAD

**Issue by AboShanab** [sigillabs/mobidex#208]
Maker amount label position is wrong.
![img](https://user-images.githubusercontent.com/12101368/52200639-5ba26000-287a-11e9-93bd-a2a5920423be.jpg)

Here we should have a list with sections like 'Info' 'About US' etc... and we should force RTL for the labels
![img_2](https://user-images.githubusercontent.com/12101368/52200640-5ba26000-287a-11e9-9115-74d9a5829b7d.jpg)

**Comment by generalpiston** [comment]
Using this issue to track the orders position bug.
