### ISSUE TITLE
Revamp my orders

### ISSUE THREAD

**Issue by generalpiston** [sigillabs/mobidex#60]
- [ ] Add forex reference amount
- [ ] Switch between my orders and available products via the header
- [ ] Add base token logo

**Comment by AboShanab** [comment]
![mobidex](https://user-images.githubusercontent.com/12101368/50747813-05c0a500-1247-11e9-8b88-6d0b04269900.jpg)

**Comment by generalpiston** [comment]
Fixed generally. Also, old.
